services:
  spark-master:
    image: spark-test
    container_name: spark-master
    env_file:
      - .env
    hostname: spark-master
    command: bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"
    ports:
      - "7077:7077" 
      - "8080:8080"
    environment:
      - SPARK_HOME=/opt/spark
    volumes:
      - ./notebooks:/workspace
      - ./src:/app/src
      - ./storage:/data
      - ./metastore:/opt/spark/metastore 
    networks:
      - spark-net

  spark-worker-1:
    image: spark-test
    container_name: spark-worker-1
    env_file:
      - .env
    hostname: spark-worker-1
    command: bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./storage:/data
    environment:
      - SPARK_HOME=/opt/spark
    networks:
      - spark-net

  spark-worker-2:
    image: spark-test
    container_name: spark-worker-2
    env_file:
      - .env
    hostname: spark-worker-2
    command: bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077"
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - ./storage:/data
    environment:
      - SPARK_HOME=/opt/spark
    networks:
      - spark-net

  jupyter:
    image: spark-test
    container_name: jupyter
    env_file:
      - .env
    hostname: jupyter
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --notebook-dir=/workspace
    ports:
      - "8888:8888"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - ./notebooks:/workspace
      - ./src:/app/src
      - ./storage:/data
      - ./metastore:/opt/spark/metastore 
    depends_on:
      - spark-master
    networks:
      - spark-net

networks:
  spark-net:
    driver: bridge